name: he-pathology
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - pillow
  - tqdm
  - pytest
  - pytorch
  - torchvision
  - torchaudio
  - pip:
      - torchstain
      - albumentations
